name: CI

env:
  DEFAULT_BRANCH: main

on:
  push:
    branches: ["${{ env.DEFAULT_BRANCH }}"]
  pull_request:
    branches: ["${{ env.DEFAULT_BRANCH }}"]

jobs:
  lint-and-format:
    name: Lint and Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: |
          uv sync --dev

      - name: Check formatting with ruff
        run: |
          uv run ruff format --check .

      - name: Run ruff linter
        run: |
          uv run ruff check .

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: |
          uv sync --dev

      - name: Unit tests
        run: |
          uv run pytest tests/unit -v --tb=short --cov=src/PROJECT_NAME --cov-report=xml --cov-report=term

      - name: Integration tests
        run: |
          uv run pytest tests/integration -v --tb=short --cov=src/PROJECT_NAME --cov-append --cov-report=xml --cov-report=term

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          flags: unittests,integrationtests
          name: codecov-umbrella
          fail_ci_if_error: false
